version: "3.8"
name: "shopping-list"
services:
  postgres-server:
    image: postgres:16-alpine
    container_name: postgres-dev
    environment:
      - POSTGRES_DB=shopping_lists
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "6543:5432"
    networks:
      - postgressqlnet
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres-server-test:
    image: postgres:16-alpine
    container_name: postgres-test
    environment:
      - POSTGRES_DB=shopping_lists
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "6542:5432"

networks:
  postgressqlnet:
    driver: bridge

volumes:
  postgres_data:
    driver: local
